SELECT F."NAME", COUNT(*)
FROM "COURSE" AS C, "FACULTY" AS F,
     (
	SELECT COUNT(*) AS SUB_CNT, SUB_C."COURSE_ID" AS SUB_ID
	FROM "COURSE" AS SUB_C, "COURSE_REGISTRATION" AS SUB_R
	WHERE SUB_C."COURSE_ID" = SUB_R."COURSE_ID"
	GROUP BY SUB_C."COURSE_ID"
	ORDER BY SUB_C."COURSE_ID"
     )
     AS SUB
WHERE C."COURSE_ID" = SUB.SUB_ID and
	C."MAX_ENROLLEES" * 0.8 < SUB.SUB_CNT and
	F."ID" = C."PROF_ID" and
	C."YEAR" <= 2018 and
	C."YEAR" >= 2013
GROUP BY F."ID"
ORDER BY COUNT(*) DESC;