SELECT S.AV, S.ID, S.GR2, S.MJR_NAME, S.CLG_NAME
FROM
  (
	SELECT S1."MAJOR_ID" AS MID1, S1."GRADE" AS GR1, MAX(T1.AVG_G) AS M
	FROM (
		SELECT G1."STUDENT_ID" AS SID1, sum(G1."GRADE" * C1."CREDIT") / sum(C1."CREDIT") AS AVG_G
		FROM "GRADE" AS G1, "COURSE" AS C1
		WHERE G1."COURSE_ID" = C1."COURSE_ID"
		GROUP BY G1."STUDENT_ID"
		ORDER BY G1."STUDENT_ID"
	     ) AS T1,
	     "STUDENTS" AS S1
	WHERE T1.SID1 = S1."STUDENT_ID" and
		S1."GRADE" >= 1 and
		S1."GRADE" <= 4
	GROUP BY S1."MAJOR_ID", S1."GRADE"
   ) AS MAX_STUDENT,
   (
	SELECT T2.SID2 AS ID, T2.AVG_G AS AV, S2."GRADE" AS GR2, S2."MAJOR_ID" AS MID2, CLG."MAJOR_NAME" AS MJR_NAME, CLG."COLLEGE_NAME" AS CLG_NAME
	FROM
	   (
		SELECT G2."STUDENT_ID" AS SID2, sum(G2."GRADE" * C2."CREDIT") / sum(C2."CREDIT") AS AVG_G
		FROM "GRADE" AS G2, "COURSE" AS C2
		WHERE G2."COURSE_ID" = C2."COURSE_ID"
		GROUP BY G2."STUDENT_ID"
		ORDER BY G2."STUDENT_ID"
	     ) AS T2,
	     "STUDENTS" AS S2, "COLLEGE" AS CLG
	WHERE T2.SID2 = S2."STUDENT_ID" and
	S2."MAJOR_ID" = CLG."MAJOR_ID"
   ) AS S
WHERE MAX_STUDENT.MID1 = S.MID2 and
 MAX_STUDENT.GR1 = S.GR2 and
 MAX_STUDENT.M = S.AV;